export { default as PrivacySetting } from './PrivacySetting'
export { default as AccountSetting } from './AccountSetting'
export { default as LanguageSetting } from './LanguageSetting'
export { default as PassCodeSetting } from './PassCodeSetting'
export { default as TermConditionSetting } from './TermConditionSetting'
export { default as AccountInformationSetting } from './AccountInformationSetting'
export { default as BasicInformationSetting } from './BasicInformationSetting'
export { default as ChangePasswordSetting } from './ChangePasswordSetting'
