export const PageName = {
  HomeTab: 'HomeTab',
  HomeScreen: 'HomeScreen',
  MenuScreen: 'MenuScreen',
  AccountScreen: 'AccountScreen',
  InAppUpdateScreen: 'InAppUpdateScreen',
  HomeStack: 'HomeStack',
  MenuStack: 'MenuStack',
  ProfileScreen: 'ProfileScreen',
  SearchScreen: 'SearchScreen',
  NotificationScreen: 'NotificationScreen',
  SplashScreen: 'SplashScreen',
  PreAuthStack: 'PreAuthStack',
  AuthStack: 'AuthStack',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  AuthPassCodeScreen: 'AuthPassCodeScreen',
  RecoveryPasswordScreen: 'RecoveryPasswordScreen',
  OnboardingScreen: 'OnboardingScreen',
  ProfileOther: 'ProfileOther',
  CaptureScreen: 'CaptureScreen',
  MediaPicker: 'MediaPicker',
  ImageEditor: 'ImageEditor',
  CreatePost: 'CreatePost',
  StoryScreen: 'StoryScreen',
}
