export const PageName = {
  HomeTab: 'HomeTab',
  HomeScreen: 'HomeScreen',
  MenuScreen: 'MenuScreen',
  AccountScreen: 'AccountScreen',
  InAppUpdateScreen: 'InAppUpdateScreen',
  HomeStack: 'HomeStack',
  MenuStack: 'MenuStack',
  SplashScreen: 'SplashScreen',
  PreAuthStack: 'PreAuthStack',
  AuthStack: 'AuthStack',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  PreAuthScreen: 'PreAuthScreen',
  AuthPassCodeScreen: 'AuthPassCodeScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  OnboardingScreen: 'OnboardingScreen',
}
