export const getStickerPacks = ({ imageSource }) => [
  {
    id: 1,
    stickers: [
      imageSource.pack1_1,
      imageSource.pack1_2,
      imageSource.pack1_3,
      imageSource.pack1_4,
      imageSource.pack1_5,
      imageSource.pack1_6,
      imageSource.pack1_7,
      imageSource.pack1_8,
      imageSource.pack1_9,
      imageSource.pack1_10,
      imageSource.pack1_11,
      imageSource.pack1_12,
      imageSource.pack1_13,
      imageSource.pack1_14,
      imageSource.pack1_15,
      imageSource.pack1_16,
    ],
  },
  {
    id: 2,
    stickers: [
      imageSource.pack2_1,
      imageSource.pack2_2,
      imageSource.pack2_3,
      imageSource.pack2_4,
      imageSource.pack2_5,
      imageSource.pack2_6,
      imageSource.pack2_7,
      imageSource.pack2_8,
      imageSource.pack2_9,
    ],
  },
  {
    id: 3,
    stickers: [
      imageSource.pack3_1,
      imageSource.pack3_2,
      imageSource.pack3_3,
      imageSource.pack3_4,
      imageSource.pack3_5,
      imageSource.pack3_6,
      imageSource.pack3_7,
    ],
  },
  {
    id: 4,
    stickers: [
      imageSource.pack4_1,
      imageSource.pack4_2,
      imageSource.pack4_3,
      imageSource.pack4_4,
      imageSource.pack4_5,
      imageSource.pack4_6,
      imageSource.pack4_7,
      imageSource.pack4_8,
      imageSource.pack4_9,
      imageSource.pack4_10,
      imageSource.pack4_11,
      imageSource.pack4_12,
      imageSource.pack4_13,
      imageSource.pack4_14,
      imageSource.pack4_15,
      imageSource.pack4_16,
    ],
  },
  {
    id: 5,
    stickers: [
      imageSource.pack5_1,
      imageSource.pack5_2,
      imageSource.pack5_3,
      imageSource.pack5_4,
      imageSource.pack5_5,
      imageSource.pack5_6,
      imageSource.pack5_7,
      imageSource.pack5_8,
      imageSource.pack5_9,
      imageSource.pack5_10,
      imageSource.pack5_11,
      imageSource.pack5_12,
      imageSource.pack5_13,
      imageSource.pack5_14,
      imageSource.pack5_15,
      imageSource.pack5_16,
    ],
  },
  {
    id: 6,
    stickers: [
      imageSource.pack6_1,
      imageSource.pack6_2,
      imageSource.pack6_3,
      imageSource.pack6_4,
      imageSource.pack6_5,
      imageSource.pack6_6,
      imageSource.pack6_7,
      imageSource.pack6_8,
      imageSource.pack6_9,
      imageSource.pack6_10,
      imageSource.pack6_11,
      imageSource.pack6_12,
      imageSource.pack6_13,
      imageSource.pack6_14,
      imageSource.pack6_15,
      imageSource.pack6_16,
    ],
  },
]
